/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;

/**
 *
 * @author Administrator
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnCenter = new javax.swing.JPanel();
        pnBot = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniQLVatTu = new javax.swing.JMenuItem();
        mniQLNhapXuat = new javax.swing.JMenuItem();
        mniQLNhanVien = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        pnCenter.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnBotLayout = new javax.swing.GroupLayout(pnBot);
        pnBot.setLayout(pnBotLayout);
        pnBotLayout.setHorizontalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnBotLayout.setVerticalGroup(
            pnBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        getContentPane().add(pnBot, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Danh mục quản lý");

        mniQLVatTu.setText("Quản lý vật tư");
        mniQLVatTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLVatTuActionPerformed(evt);
            }
        });
        jMenu1.add(mniQLVatTu);

        mniQLNhapXuat.setText("Quản lý nhập xuất");
        mniQLNhapXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNhapXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mniQLNhapXuat);

        mniQLNhanVien.setText("Quản lý nhân viên");
        mniQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQLNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(mniQLNhanVien);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Báo cáo");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Hệ thống");

        jMenuItem5.setText("Đổi mật khẩu");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Đăng xuất");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        jMenuItem7.setText("Hướng dẫn");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Thông tin sản phẩm");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniQLVatTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLVatTuActionPerformed
        pnCenter.removeAll();
        pnCenter.revalidate();
        pnCenter.add(new pnQuanLyTonKho(), BorderLayout.CENTER);
    }//GEN-LAST:event_mniQLVatTuActionPerformed

    private void mniQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNhanVienActionPerformed
        pnCenter.removeAll();
        pnCenter.revalidate();
        pnCenter.add(new pnQuanLyNhanVien(), BorderLayout.CENTER);
    }//GEN-LAST:event_mniQLNhanVienActionPerformed

    private void mniQLNhapXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQLNhapXuatActionPerformed
        pnCenter.removeAll();
        pnCenter.revalidate();
        pnCenter.add(new pnQuanLyNhapXuat(), BorderLayout.CENTER);
    }//GEN-LAST:event_mniQLNhapXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem mniQLNhanVien;
    private javax.swing.JMenuItem mniQLNhapXuat;
    private javax.swing.JMenuItem mniQLVatTu;
    private javax.swing.JPanel pnBot;
    private javax.swing.JPanel pnCenter;
    // End of variables declaration//GEN-END:variables
}
