/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import library.LibraryPropertiesFile;
import library.LoginDB;
import library.NhapXuatDB;
import library.TruyVanDB;

/**
 *
 * @author Administrator
 */
public class FrSuaNguoiDung extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FrSuaNguoiDung
     */
    public FrSuaNguoiDung() {
        initComponents();
        try {
            khoitaoCombobox();
        } catch (SQLException ex) {
            Logger.getLogger(FrSuaNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        q = Integer.parseInt(prop.getProperty("quyen"));
        if (q == 2) {
            taikhoan = prop.getProperty("taikhoan");
            System.out.print(taikhoan);
            comboTK.removeAllItems();
            comboTK.addItem(taikhoan);
            comboTK.disable();
            comboQuyen.setSelectedIndex(1);
            comboQuyen.disable();
        }
        comboTK.addActionListener(this);
        comboQuyen.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbtk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbq = new javax.swing.JLabel();
        comboQuyen = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtMK1 = new javax.swing.JPasswordField();
        txtMK2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtMK3 = new javax.swing.JPasswordField();
        lbTB = new javax.swing.JLabel();
        comboTK = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sửa thông tin người dùng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 255, 0))); // NOI18N
        jPanel1.setEnabled(false);

        lbtk.setText("Tên người dùng : ");

        jLabel2.setText("Mật khẩu cũ : ");

        jLabel3.setText("Mật khẩu mới :");

        lbq.setText("Quyền :");

        comboQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân viên", " " }));
        comboQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQuyenActionPerformed(evt);
            }
        });

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Thoát");
        jPanel2.add(jButton2);

        txtMK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMK2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nhập lại mật khẩu mới :");

        txtMK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMK3ActionPerformed(evt);
            }
        });

        lbTB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTB.setForeground(new java.awt.Color(255, 0, 51));

        comboTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân viên", " " }));
        comboTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbtk, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbq)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMK3)
                    .addComponent(txtMK2)
                    .addComponent(txtMK1)
                    .addComponent(comboTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(lbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbtk, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbq))
                .addGap(23, 23, 23)
                .addComponent(lbTB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMK2ActionPerformed

    private void comboQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboQuyenActionPerformed

    private void txtMK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMK3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMK3ActionPerformed

    private void comboTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if ("".equals(txtMK1.getText())
                || "".equals(txtMK3.getText())
                || "".equals(txtMK2.getText())) {
            lbTB.setText("Vui lòng nhập đầy đủ thông tin");
        } else {
            LoginDB lg = new LoginDB();
            String mk = txtMK1.getText();
            String mkn = txtMK2.getText();
            if (q == 1) 
            {
                taikhoan = (String) comboTK.getSelectedItem();
                q = comboQuyen.getSelectedIndex()+1;
            }
            ResultSet rs = null;
            rs = lg.checkLogin(taikhoan, mk);
            try {
                if (!rs.next()) {
                    lbTB.setText("mật khẩu không đúng!");
                } else {
                    if (!txtMK3.getText().equals(txtMK2.getText())) {
                        lbTB.setText("Nhập mật khẩu không trùng");
                    }
                    else
                    {
                        lg.doiMK(taikhoan,mkn,q);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrSuaNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSuaNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSuaNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSuaNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSuaNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSuaNguoiDung().setVisible(true);
            }
        });
    }

    public void khoitaoCombobox() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        DefaultComboBoxModel modelQuyen = new DefaultComboBoxModel();
        ResultSet result;
        result = nx.taikhoan();
        modelQuyen.addElement("Quản Lý");
        modelQuyen.addElement("Nhân Viên");
        while (result.next()) {
            model.addElement(result.getString(2));
        }
        comboTK.setModel(model);
        comboQuyen.setModel(modelQuyen);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == comboTK) {
            taikhoan = comboTK.getItemAt(comboTK.getSelectedIndex());
        }
        if (e.getSource() == comboQuyen) {
            quyen = comboQuyen.getSelectedIndex() + 1;
            System.out.print(quyen);
        }
    }

    String taikhoan = "";
    DefaultComboBoxModel model1 = new DefaultComboBoxModel();
    TruyVanDB nx = new TruyVanDB();
    Properties prop = LibraryPropertiesFile.readFileConfig("login.properties");
    String idNV;
    int quyen;
    int q;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboQuyen;
    private javax.swing.JComboBox<String> comboTK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTB;
    private javax.swing.JLabel lbq;
    private javax.swing.JLabel lbtk;
    private javax.swing.JPasswordField txtMK1;
    private javax.swing.JPasswordField txtMK2;
    private javax.swing.JPasswordField txtMK3;
    // End of variables declaration//GEN-END:variables
}
