/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import library.LibraryPropertiesFile;
import library.NhapXuatDB;
import library.TienIch;

/**
 *
 * @author Administrator
 */
public class pnBaoCaoXuat extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form pnBaoCaoXuat
     */
    public pnBaoCaoXuat() throws SQLException {
        initComponents();
        tableNhapTong.setModel(tableModel);
        khoitaoCombobox();
        comboNhanVien.addActionListener(this);
        quyen = prop.getProperty("quyen");
        if ("2".equals(quyen)) {
            comboNhanVien.disable();
            idNV = prop.getProperty("idnv");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateTu = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateDen = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        comboNhanVien = new javax.swing.JComboBox<>();
        btBaoCao = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNhapTong = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Báo Cáo Nhập", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204)))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Báo cáo hàng hóa nhập");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Từ:");
        jPanel4.add(jLabel2);
        jPanel4.add(dateTu);

        jLabel3.setText("Đến:");
        jPanel4.add(jLabel3);
        jPanel4.add(dateDen);

        jLabel4.setText("Nhân viên");
        jPanel4.add(jLabel4);

        comboNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(comboNhanVien);

        btBaoCao.setText("Báo cáo");
        btBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBaoCaoActionPerformed(evt);
            }
        });
        jPanel4.add(btBaoCao);

        jTextField2.setPreferredSize(new java.awt.Dimension(100, 28));
        jPanel4.add(jTextField2);

        jButton4.setText("Tìm");
        jPanel4.add(jButton4);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tableNhapTong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableNhapTong);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton2.setText("In báo cáo");
        jPanel3.add(jButton2);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBaoCaoActionPerformed
        // TODO add your handling code here:
        TienIch ti = new TienIch();
        String tu, den;
        tu = ti.getDate(dateTu);
        den = ti.getDate(dateDen);

        loadData(tu, den);
    }//GEN-LAST:event_btBaoCaoActionPerformed

    String idNV = "";
    NhapXuatDB nx = new NhapXuatDB();
    private DefaultTableModel tableModel = new DefaultTableModel();
    DefaultComboBoxModel model1 = new DefaultComboBoxModel();
    Properties prop = LibraryPropertiesFile.readFileConfig("login.properties");
    String quyen;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBaoCao;
    private javax.swing.JComboBox<String> comboNhanVien;
    private com.toedter.calendar.JDateChooser dateDen;
    private com.toedter.calendar.JDateChooser dateTu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableNhapTong;
    // End of variables declaration//GEN-END:variables

    public void loadData(String tu, String den) {

        ResultSet result;
        result = nx.baoCaoXuatNV(tu, den, idNV);
        String[] colsName = {"STT", "Tên sản phẩm", "Số lượng", "Đơn vị", "Đơn giá", "Ngày Xuất", "Người Xuất"};
        tableModel.setColumnIdentifiers(colsName); // Đặt tiêu đề cho bảng theo các giá trị của mảng colsName
        int i = 1;
        clearOldDataInTableModel();
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[7];
                rows[0] = String.valueOf(i); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(8);
                rows[2] = result.getString(4);
                rows[3] = result.getString(9);
                rows[4] = String.valueOf(result.getInt(25));
                rows[5] = result.getString(3);
                rows[6] = result.getString(11);

                i++;
                // lấy dữ liệu tai cột số 2 ứng với tên hàng
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
                // mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void khoitaoCombobox() throws SQLException {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        ResultSet result;
        result = nx.comboboxDataNV();
        model.addElement("Tất cả");
        model1.addElement("");
        while (result.next()) {
            model.addElement(result.getString(2));
            model1.addElement(result.getString(1));
        }
        comboNhanVien.setModel(model);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == comboNhanVien) {
            idNV = model1.getElementAt(comboNhanVien.getSelectedIndex()).toString();
        }
        /*if (e.getSource() == comboTen) {
            comboID.setSelectedIndex(comboTen.getSelectedIndex());
        }*/
    }

    private void clearOldDataInTableModel() {
        //Xóa theo cách 2, hiệu suất làm việc cao hơn
        int rowCount = tableModel.getRowCount();
        for (int i = rowCount; i > 0; i--) {
            tableModel.removeRow(i - 1);
        }
    }

}
