/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import library.LibraryPropertiesFile;
import library.NhapXuatDB;
import library.TienIch;

/**
 *
 * @author Administrator
 */
public class pnBaoCaoNhap extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form pnBaoCaoXuat
     */
    public pnBaoCaoNhap() throws SQLException {
        initComponents();
        tableNhapNV.setModel(tableModel);
        khoitaoCombobox();
        comboNhanVien.addActionListener(this);
        quyen = prop.getProperty("quyen");
        
        if ("2".equals(quyen)) 
        {
            comboNhanVien.disable();
            idNV = prop.getProperty("idnv");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateTu = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateDen = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        comboNhanVien = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNhapNV = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Báo cáo Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        setForeground(new java.awt.Color(0, 0, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Báo cáo nhập kho");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Từ:");
        jPanel4.add(jLabel2);
        jPanel4.add(dateTu);

        jLabel3.setText("Đến:");
        jPanel4.add(jLabel3);
        jPanel4.add(dateDen);

        jLabel4.setText("Nhân viên");
        jPanel4.add(jLabel4);

        comboNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(comboNhanVien);

        jButton1.setText("Báo cáo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tableNhapNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableNhapNV);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton2.setText("In báo cáo");
        jPanel3.add(jButton2);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("Báo Cáo Nhập ");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TienIch ti = new TienIch();
        String tu, den;
        tu = ti.getDate(dateTu);
        den = ti.getDate(dateDen);
        loadData(tu,den,idNV);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void loadData(String tu, String den,String nv) {
       
        ResultSet result;
        result = nx.baoCaoNhapNV(tu, den,idNV);
        String[] colsName = { "STT", "Tên sản phẩm", "Số lượng", "Ngày sản xuất", "Hạn sữ dụng", "Giá", "Ngày nhập","Người nhập", "Vị trí"};
        tableModel.setColumnIdentifiers(colsName); // Đặt tiêu đề cho bảng theo các giá trị của mảng colsName
        int i =1;
        clearOldDataInTableModel();
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[9];
                rows[0] = String.valueOf(i); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(13); 
                rows[2] = result.getString(4); 
                rows[3] = result.getString(5); 
                rows[4] = result.getString(6); 
                rows[5] = String.valueOf(result.getInt(7));
                rows[6] = result.getString(3); 
                rows[7] = result.getString(16); 
                rows[8] = result.getString(9); 
                i++;
                // lấy dữ liệu tai cột số 2 ứng với tên hàng
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
                // mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
 
        
    }

    private void clearOldDataInTableModel(){
        //Xóa theo cách 2, hiệu suất làm việc cao hơn
        int rowCount = tableModel.getRowCount();
        for(int i = rowCount;i>0;i--){
            tableModel.removeRow(i-1);
        }
    }

    public void khoitaoCombobox() throws SQLException
    {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        ResultSet result;
        result = nx.comboboxDataNV();
        model.addElement("Tất cả");
        model1.addElement("");
        while(result.next()) 
        {
            model.addElement(result.getString(2)); 
            model1.addElement(result.getString(1)); 
        }
        comboNhanVien.setModel(model);
    }
    
     @Override
     public void actionPerformed(ActionEvent e) {
        if (e.getSource() == comboNhanVien) {
            idNV = model1.getElementAt(comboNhanVien.getSelectedIndex()).toString();
        }
        /*if (e.getSource() == comboTen) {
            comboID.setSelectedIndex(comboTen.getSelectedIndex());
        }*/
    }
    
    String idNV="";
    NhapXuatDB nx = new NhapXuatDB();
    private DefaultTableModel tableModel = new DefaultTableModel();
    DefaultComboBoxModel model1 = new DefaultComboBoxModel();
    Properties prop = LibraryPropertiesFile.readFileConfig("login.properties");
    String quyen;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboNhanVien;
    private com.toedter.calendar.JDateChooser dateDen;
    private com.toedter.calendar.JDateChooser dateTu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableNhapNV;
    // End of variables declaration//GEN-END:variables
}
