/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import library.NhapXuatDB;

/**
 *
 * @author Administrator
 */
public class pnQuanLyTonKho extends javax.swing.JPanel {

    /**
     * Creates new form Quanlyvattu
     */
    public pnQuanLyTonKho() {
        initComponents();
        //tableTonKho.setModel(tableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txts = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btCatNhapLai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTonKho = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Quản Lý Vật Tư", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255)))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nhập dữ liệu cần tìm");
        jPanel1.add(jLabel2);

        txts.setPreferredSize(new java.awt.Dimension(150, 28));
        jPanel1.add(txts);

        jButton2.setText("Tìm");
        jButton2.setPreferredSize(new java.awt.Dimension(49, 28));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btCatNhapLai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCatNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie-chart-icon.png"))); // NOI18N
        btCatNhapLai.setText("Refresh");
        btCatNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCatNhapLaiActionPerformed(evt);
            }
        });
        jPanel4.add(btCatNhapLai);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tableTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableTonKho);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btCatNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCatNhapLaiActionPerformed
        xoabang();
        loadData();
    }//GEN-LAST:event_btCatNhapLaiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ResultSet result;
        xoabang();
        DefaultTableModel tableModel = new DefaultTableModel();
        String s = txts.getText();
        result = nx.timTonKho(s);
        String[] colsName = {"STT", "Tên sản phẩm", "SL Hiện có", "Ngày sản xuất", "Hạn sữ dụng", "Giá", "Vị trí",};
        tableModel.setColumnIdentifiers(colsName); // Đặt tiêu đề cho bảng theo các giá trị của mảng colsName
        int i = 1;
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[9];
                rows[0] = String.valueOf(i); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(13);                
                rows[2] = result.getString(11);                
                rows[3] = result.getString(5);                
                rows[4] = result.getString(6);                
                rows[5] = String.valueOf(result.getInt(7));
                rows[6] = result.getString(9);                
                
                i++;
                // lấy dữ liệu tai cột số 2 ứng với tên hàng
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
                // mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
            }
            tableTonKho.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void loadData() {  
        ResultSet result;
        DefaultTableModel tableModel = new DefaultTableModel();
        result = nx.tonKho();
        String[] colsName = {"STT", "Tên sản phẩm", "SL Hiện có", "Ngày sản xuất", "Hạn sữ dụng", "Giá", "Vị trí",};
        tableModel.setColumnIdentifiers(colsName); // Đặt tiêu đề cho bảng theo các giá trị của mảng colsName
        int i = 1;
        try {
            while (result.next()) { // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[9];
                rows[0] = String.valueOf(i); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(13);                
                rows[2] = result.getString(11);                
                rows[3] = result.getString(5);                
                rows[4] = result.getString(6);                
                rows[5] = String.valueOf(result.getInt(7));
                rows[6] = result.getString(9);                
                i++;
                // lấy dữ liệu tai cột số 2 ứng với tên hàng
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel để hiện thị lên jtable
                // mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update lại trên frame
            }
            tableTonKho.setModel(tableModel);
        } catch (SQLException e) {
            e.printStackTrace();
        }        
    }
    
    private void xoabang() {    
            
    }
    String today, ngaySX, hanSuDung, ngayNhap, idNhap, viTri, idNhanVien, idHang, tenHang;
    int soLuong, gia;
    NhapXuatDB nx = new NhapXuatDB();
    //private DefaultTableModel tableModel = new DefaultTableModel();
    private DefaultTableModel tableModel1 = new DefaultTableModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCatNhapLai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableTonKho;
    private javax.swing.JTextField txts;
    // End of variables declaration//GEN-END:variables
}
